name: Eleventy Build Staging
on:
  push:
    branches:
      - staging

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: staging
      - name: Build
        uses: cagov/actions-eleventy@2.0
        with:
          args: --formats=html,njk --input ./pages --output ./docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PublishBranch: deploy_staging
          PublishDir: ./docs
          publish_branch: deploy_staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
