name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cagov/actions-eleventy@v1.4.1
        with:
          args: --formats=html --input ./pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: ./docs 
          PUBLISH_BRANCH: gh_pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
